### PR TITLE
texture integer

### PR DESCRIPTION
**Pull request by shrekshao**
Potential fixing needed: 
- strange texture boarder, might be problems of texel to pixel mapping
- FireFox Error: WebGL: texImage2D: Driver ran out of memory during upload.
- Christ's sample aborts during operation, due to image format error. 
- But, still pull request as a stopgap of 10 samples for 2015 -_-

### CODE REVIEW

**Comment by pjcozzi** [comment]
> assets/img/kueken7_rgb10a2u.dds

Where did this file come from?  What is the plan for it?  For dds, you may want to use something like https://github.com/toji/texture-tester/blob/master/js/webgl-texture-util.js, but I would only use compressed textures for samples specifically about them to keep everything simple.

By the way, this may be of interest to you: http://toji.github.io/texture-tester/

**Comment by pjcozzi** [comment]
You could also procedurally generate a texture in code for some of these examples.

**Comment by pjcozzi** [comment]
Is this the expected output?

image

**Comment by shrekshao** [comment]
oh ,for the dds image, i forgot to clean it.... I still use the png for this sample

Yes, i deliberately multiply a 32 and divide a 32 to demonstrate its an integer texture

**Comment by pjcozzi** [comment]
OK, so I think this is ready to merge.  Do you agree?

**Comment by shrekshao** [comment]
Yes

**Pull request merged**
