### PR TITLE
draw_instanced: replace getAttribLocation with layout location

### PR DESCRIPTION
**Pull request by shrekshao**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Did you test this carefully?  In my test, this only worked for attribute location 0.

For example, change it to 1, and it did not work for me.

It _could_ be because attribute 0 is required in WebGL 2 (not having it in WebGL 1, just yields a performance warning on most implementations).

Just for testing, add a few more attributes and verify this works as expected.

**Comment by shrekshao** [comment]
Did u mean testing the location starting from 1 instead of 0?

For multiple case, it works fine in glsl discard 0 for pos, 1 for texcoord

**Comment by kenrussell** [comment]
I tested changing the location from 0 to 1 in the shader and in the enableVertexAttribArray and vertexAttribPointer calls, and the sample continued to work. If there seem to be any problems with layout qualifiers not working please let us know.

**Comment by pjcozzi** [comment]
@kenrussell that worked for me in Canary (Chrome 49), but not stable (Chrome 47) so this is all good.  We should be using Canary for this project anyway.

**Comment by kenrussell** [comment]
@pjcozzi yes, there's hardly any point in testing WebGL 2.0 in any Chrome branch except Canary.

**Pull request merged**
