### PR TITLE
texture 2d array

### PR DESCRIPTION
**Pull request by shrekshao**
- Not a port from ogl sample
- I will try to update the new feature list according to OpenGL ES 3.0 as soon as possible

### CODE REVIEW

**Comment by shrekshao** [comment]
This is ready besides the artifacts on the edge

**Comment by pjcozzi** [comment]
Great sample!  I cleaned up the render loop in 1f96091af63a700173bb2052365987e1ecaf17b8.

Any idea about the artifact?  Does it have anything to do about the size of the texture or texture filtering limitations for texture arrays?  Or perhaps all the pixel pushing with canvas?  Why not combine the textures into one image file and avoid all the client-side processing (this is what most engines would do)?

**Comment by shrekshao** [comment]
Yeah, i once saw this question online, I will fix it but will take some time

Yeah, combining the data into one image is a great idea

**Comment by shrekshao** [comment]
Ready for review
- Combine images into one file
- Use background color instead of transparency
  - The transparent border artifacts has been mentioned by several questions, but I fail to fix it using the given solution. Since it might be an issue of the image itself, I decide to skip this at this moment to move forward

**Comment by pjcozzi** [comment]
Looks good.  I'm still not thrilled with the `Image -> Canvas -> ArrayBuffer -> Uint8Array` conversion to call `texImage3D`, but it looks like that is how it has to be done.

**Pull request merged**
