### PR TITLE
discard onunload clean

### LINKED ISSUE #87: discard deleteing WebGL context windows.onunload functions
No necessary for doing this when windows is closed because browsers will take care of that. And explicit doing so will slow down the process. Thanks to Ken.

### PR DESCRIPTION
**Pull request by shrekshao**
fix #87 
- `glsl_flat_smooth_interpolators.html` and `texture_vertex.html` will be fixed in gltf_loader branch, due to buffer change

### CODE REVIEW

**Comment by pjcozzi** [comment]
:+1:

**Comment by kenrussell** [comment]
Thanks, looks good. I wonder whether a small section in the README would be warranted describing why developers should manually delete WebGL resources rather than letting the garbage collector do it. You could link to https://www.khronos.org/registry/webgl/specs/latest/1.0/#3 . We could add a name for that section, and add a rationale, too. Let me know.

**Comment by pjcozzi** [comment]
Good idea IMO.

**Comment by kenrussell** [comment]
Thanks Patrick. Which part in particular? Do you want an update to the WebGL spec?

**Comment by pjcozzi** [comment]
Only if you think it is warranted.  Just a short section in the README.md here as you suggested would be a nice start.

**Comment by kenrussell** [comment]
OK. Please file an issue on KhronosGroup/WebGL if you want a "rationale" note added. Thanks.

**Pull request merged**
