### PR TITLE
Fix texture derivative perspective error, gl-matrix version, not used variable in glsl

### PR DESCRIPTION
**Pull request by shrekshao**
- The perspective is wrong. `lookAt` in gl-Matrix generate a frustum matrix, not simply a view matrix. Fixed. The same problem remains in `texture_vertex` @trungtle 
- Use gl-matrix-min.js of version 2.x instead of the 1.x version
- Delete a never used input in the vertex shader
- Delete unused fract in fragment shader
- Fix the mirrored texcoord on the back and top face

### CODE REVIEW

**Comment by trungtle** [comment]
Nice catch!

-Tr

**Comment by shrekshao** [comment]
One more thing: since you use textureLod to select level of mipmap, I think you should `gl.generateMipmap(gl.TEXTURE_2D);` first? Right?, or there is only one level?

**Comment by trungtle** [comment]
This looks great for the fix. I removed the textureLevel function inside frag shader since I don't think there's a need for it anyway (not using mipmap)

**Comment by pjcozzi** [comment]
Thanks!

**Pull request merged**
