### PR TITLE
Issue #37: Removed experimental-webgl2 context

### PR DESCRIPTION
**Pull request by trungtle**
@pjcozzi @shrekshao Ready for review. Fixed for #37

### CODE REVIEW

**Comment by kenrussell** [comment]
Thanks for this cleanup. LGTM for what it's worth.

**Comment by pjcozzi** [comment]
:+1: 

Nice and clean!

**Comment by pjcozzi** [comment]
Also, just a reminder to please delete a branch after the pull request is merged.  Once you hit the merge button and confirm the merge, a button appears to delete the branch.  Click it.

**Comment by shrekshao** [comment]
Oh yeah, my bad. Thanks for this note

**Pull request merged**
