### PR TITLE
[texture_srgb] - Implemented

### PR DESCRIPTION
**Pull request by trungtle**
This sample demonstrates use of srgb internal format for a texture (not a direct port from Christophe's sample).

### CODE REVIEW

**Comment by pjcozzi** [comment]
Could we make this example slightly more interesting, perhaps by including a simple filter in the fragment shader that is commonly done in sRGB space?

**Comment by trungtle** [comment]
What do you think, would something like an sRGB to linear filter interesting for this sample? I'm not familiar with what is commonly done in sRGB space.

**Comment by trungtle** [comment]
Just a conceptual question, would the call 

```
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
```

already applied filtering to the texture already? So would that still be neccessary to add another filter in the fragment shader? I'm just still new to this.

**Comment by trungtle** [comment]
Okay, I added rgb to srgb conversion and contrast, saturation, brightness in frag shader code. Still no frame buffer yet, but this would make it more interesting of a sample.

**Comment by pjcozzi** [comment]
This doesn't run on Windows:

> Structures containing samplers not currently supported in D3D.

What did we do in the other sample with a struct?  Remove the struct?

**Comment by pjcozzi** [comment]
> Just a conceptual question, would the call 
> 
> ```
>             gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
>             gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
> ```
> 
> already applied filtering to the texture already? So would that still be neccessary to add another filter in the fragment shader? I'm just still new to this.

This sets the fixed function state for the hardware texture filtering that happens "inside" the call to `texture` (but not `texelFetch`, which is explicitly for reading texels without filtering them).

It's still fine to apply another type of filter, like bloom, after reading the filtered texel.

**Comment by kenrussell** [comment]
FYI @Oletus mentioned that he's working on lifting the limitations in ANGLE's HLSL backend around texture functions, probably including whether samplers can be included in structs.

**Comment by pjcozzi** [comment]
@trungtle for more on sRGB, see
- http://opengl.datenwolf.net/gltut/html/Texturing/Tutorial%2016.html
- http://http.developer.nvidia.com/GPUGems3/gpugems3_ch24.html

**Comment by pjcozzi** [comment]
Good news, @kenrussell @Oletus!

@trungtle given this, we can keep the struct if you want and just label it as not working on Windows for now in the table.

**Comment by kenrussell** [comment]
Yes, keeping the struct would be ideal -- it'll be necessary to make this work in ANGLE's D3D backend eventually.

**Comment by trungtle** [comment]
I'll keep the struct in for now and will update README soon. Thank you for checking on this! 

@pjcozzi I also added gamma correction in ed89e3e for a more interesting sample.

**Comment by pjcozzi** [comment]
Merge master into this branch.  There is a conflict.

**Comment by trungtle** [comment]
I'm sorry that this took long to update. I applied a gaussian filter and did some math in linear space before converting back into sRGB color space. Added a comment in the fragment shader to explain the motivation behind it. This should be ready to merge.

**Comment by pjcozzi** [comment]
Looks good!

**Pull request merged**
