### PR TITLE
vertex format

### PR DESCRIPTION
**Pull request by trungtle**
Not sure how useful this sample looks for the purpose of demonstrating new vertex format, but this is one listed in our roadmap. I'm passing different vertex formats for the cube geometry when setting up vertex array.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Can we do one with half floats, which will be widely used for normals and texture coordinates?  Not sure if/how these are supported by typed arrays.

**Comment by kenrussell** [comment]
It would be good to test handling of half-floats. These aren't handled directly by typed arrays (there's no Float16Array) but you can manually construct the bit patterns resulting from converting numbers to 16-bit floats. See sdk/tests/deqp/framework/common/tcuFloat.js in the WebGL workspace for some (complex, but complete) code. There is a conversion table somewhere which is less code, but I can't find it at the moment. Once the data is uploaded into a buffer, you can reference it as half-floats.

**Comment by pjcozzi** [comment]
Thanks @kenrussell.

@trungtle / @shrekshao if we had enough time it would be nice to make a WebGL 2 utility library for things like this...could be a project for other students for another semester.

**Comment by trungtle** [comment]
@kenrussell I took a look at the implementation in tcuFloat, thanks for pointing out. @pjcozzi I will try to get the half float conversion done and update this pull request.

**Comment by pjcozzi** [comment]
Should we close this as duplicate with #96?

**Pull request merged**
