### PR TITLE
replace view source link

### LINKED ISSUE #92: Replace "View source" link
Instead of opening up the page's source, it could be more instructive to open a link to the page on GitHub, including the highlighted section of relevant code, e.g., https://github.com/WebGLSamples/WebGL2Samples/blob/master/samples/texture_2d_array.html#L143-L157

### PR DESCRIPTION
**Pull request by shrekshao**
fix #92 
Pending for other samples highlighted lines tag

### CODE REVIEW

**Comment by trungtle** [comment]
I have updated the view source links for the rest of the samples and also added descriptions for all the other samples that were left. Ready for review.

**Comment by shrekshao** [comment]
....why it fails the travis check....

**Comment by trungtle** [comment]
Sorry, it was a missing leading zero

**Comment by pjcozzi** [comment]
:+1:

**Pull request merged**
