### PR TITLE
Sample showing transform feedback input to instanced draw

### PR DESCRIPTION
**Pull request by tsherif**
@shrekshao @kenrussell Done :)

### CODE REVIEW

**Comment by kenrussell** [comment]
Very nice. Skimming through this, it looks good, but @shrekshao should fully review and merge it.

**Comment by shrekshao** [comment]
Hopefully by the end of this week. At the End of semester and whole student
career....

**Comment by tsherif** [comment]
Haha, no worries :) Good luck, @shrekshao!

**Comment by kenrussell** [comment]
Good luck @shrekshao !

**Comment by kenrussell** [comment]
Good luck @shrekshao !

**Comment by shrekshao** [comment]
@tsherif @kenrussell 
I have a different understanding on how the combining of transform feedback and draw instance should work. 
Tarek's sample basically applies transform feedback to the geometry vertices buffer (`trianglePositions`). There are two problems: 
* The buffer itself is small (6 floats), which is not very necessary to use transform feedback
* The purpose of this operation is like procedural generation of the geometry which can be useful when we have a complex geometry and needed some dynamic effects (e.g. dynamic vertex displacement). But this has weak relation with draw instance. 

So I made some modification based on Tarek's code. It is now a simple agent aimlessly wandering simulation and draw a geometry for each agent instead of rasterize points, which is a better scenario (at least from my point of view) because: 
* Apply the transform feedback on a large attribute buffer (offset and rotation, the size of which are proportional to the number of instances)
* Has a stronger relation with draw instance. Because the geometry of agent can be complex, e.g. a human model when doing crowd simulation. 

The new pull request is #149 . Here's a preview:

**Pull request merged**
