### PR TITLE
draw image space

### PR DESCRIPTION
**Pull request by shrekshao**
- without gl_VertexID implementation

### CODE REVIEW

**Comment by pjcozzi** [comment]
What is the point of this sample?  What is specific to WebGL 2?  Is it to show the use of `gl_VertexID`?

**Comment by shrekshao** [comment]
I think it's showing gl_Fragcoord. Yeah i should go and check if it's
already supported in webgl 1

**Comment by pjcozzi** [comment]
`gl_FragCoord` is in WebGL 1.  I would rather change this to use `gl_VertexID` and then just list it as broken for now in the table.

**Comment by trungtle** [comment]
I don't think gl_VertexID is defined in this glsl version. I can't find the specifics on it. @pjcozzi I've been following the es_spec_3.0.4 but is it guaranteed to be the same with the glsl for WebGL 2?

**Comment by kenrussell** [comment]
Yes, gl_VertexID is defined in this GLSL version. See GLSL ES 3.00.4, section 7.1, "Vertex Shader Special Variables". "While the variable gl_VertexID is always present, its value is not always defined."

**Comment by shrekshao** [comment]
Ok, so `gl_VertexID` is in this GLSL version but currently the browser hasn't got the full support for it. Since without `gl_VertexID` this sample will be meaningless to WebGL 2, shall I close this pull request later?

**Comment by pjcozzi** [comment]
I am fine with merging it and then marking it as not working in the table in README.md, since the `gl_vertexID` is such a small change from what you have now, I suspect it will work when the browser support is there.

**Comment by shrekshao** [comment]
labeled gl_Vertex in README, ready to merge

**Comment by pjcozzi** [comment]
I meant to update the table in README.md _and_ to change the sample to use `gl_VertexID`.

**Comment by shrekshao** [comment]
Ready: Revert to use gl_VertexID

**Comment by pjcozzi** [comment]
Thanks.

**Pull request merged**
