### PR TITLE
Texture offset 

### PR DESCRIPTION
**Pull request by trungtle**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Is this the expected output?  Given the spline in the fragment shader I would not expect this.

image

**Comment by trungtle** [comment]
This is what I see from the original sample:
screen shot 2016-01-13 at 7 15 18 pm

In this sample I just translated the catmulRom filter codes directly and applied on both images, but the one on the left is using texelFetchOffset (with 0 offset) and the one on the right is using textureOffset. The quality of the right one is better if you look closely at the edge of the sword (I believe because it is normalized through the textureOffset call).

**Comment by pjcozzi** [comment]
Ah, I see.  The splines are being used for filtering for a 16-tap kernel.

So are you OK with the output of your WebGL version; the viewports are swapped, was that intentional?

**Comment by trungtle** [comment]
I swapped back the viewport so it is consistent with Christophe's sample.

**Comment by pjcozzi** [comment]
Looks good!

**Pull request merged**
