### PR TITLE
glsl flat smooth interpolators

### PR DESCRIPTION
**Pull request by shrekshao**
- Use webgl-obj-loader. License and README credits added. 
- Use gl-matrix-min.js 2.0. The gl-matrix.js in repo at present is version 1.x. Since there's a issue with the texture-3d sample using the new 2.0 gl-matrix, I will remain the old version gl-matrix there and come back later to fix that
- Firefox is workding but there are some weird artifacts. It's correct with chrome.

### CODE REVIEW

**Comment by pjcozzi** [comment]
> Use gl-matrix-min.js 2.0. The gl-matrix.js in repo at present is version 1.x. Since there's a issue with the texture-3d sample using the new 2.0 gl-matrix, I will remain the old version gl-matrix there and come back later to f

OK, submit an issue for this.  We want to fix this before a lot of people start looking at this repo since it will be confusing and makes us look a bit sloppy.

**Comment by pjcozzi** [comment]
> assets/obj/di_model_tri.obj

@shrekshao I just want to confirm that you created this model?  We need to rights to use any asset in this repo.

**Comment by pjcozzi** [comment]
Great job with this sample.

Just those questions, and this is ready to merge.

**Comment by shrekshao** [comment]
Yes, it is a self-created model

**Pull request merged**
