### PR TITLE
query occlusion

### PR DESCRIPTION
**Pull request by shrekshao**

### CODE REVIEW

**Comment by shrekshao** [comment]
Ready for a review

**Comment by pjcozzi** [comment]
Looks good.  Made a few tweaks in 0a05a20ec000bf7bf022a6a871abd6961b5f44d4.

@kenrussell `gl.getQueryParameter(query, gl.QUERY_RESULT)` returns `1` in Chrome 47, but `0` in 49.  Do you want us to submit an issue?

``` javascript
gl.beginQuery(gl.ANY_SAMPLES_PASSED, query);
gl.drawArraysInstanced(gl.TRIANGLES, 0, 3, 2);
gl.endQuery(gl.ANY_SAMPLES_PASSED);

var samplesPassed = gl.getQueryParameter(query, gl.QUERY_RESULT);
```

**Comment by pjcozzi** [comment]
Sorry, tweaks were in a1a902ad3c36ca8ba2b984107bd441b83f0d00b2, not 0a05a20ec000bf7bf022a6a871abd6961b5f44d4.

**Comment by kenrussell** [comment]
@pjcozzi this is happening because of a spec and implementation change. In WebGL 2.0, compared to ES 3.0, queries' results must not be made available in the current frame. Please see https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.23 and https://www.khronos.org/registry/webgl/specs/latest/2.0/#GET_QUERY_PARAMETER . See also sdk/tests/conformance2/query/occlusion-query.html and sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js for example tests which both verify that queries' results aren't available in the current frame, and become available in subsequent frames.

**Comment by pjcozzi** [comment]
Thanks for the detailed explanation, @kenrussell.  I fixed our example in #23.

**Pull request merged**
